export enum UserDataActionTypes {
    GET_USER_DATA = "GET_USER_DATA",
    GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS",
    GET_USER_DATA_ERROR = "GET_USER_DATA_ERROR",
    SET_USER_DATA = "SET_USER_DATA",
    SET_USER_DATA_SUCCESS = "SET_USER_DATA_SUCCESS",
    SET_USER_DATA_ERROR = "SET_USER_DATA_ERROR"
}

export enum UserProfileActionTypes {
    GET_USER_PROFILE = "GET_USER_PROFILE",
    GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS",
    GET_USER_PROFILE_ERROR = "GET_USER_PROFILE_ERROR",
    SET_USER_PROFILE = "SET_USER_PROFILE",
    SET_USER_PROFILE_SUCCESS = "SET_USER_PROFILE_SUCCESS",
    SET_USER_PROFILE_ERROR = "SET_USER_PROFILE_ERROR"
}

export enum GalleryMediaActionTypes {
    GET_GALLERY_MEDIA = "GET_GALLERY_MEDIA",
    GET_GALLERY_MEDIA_SUCCESS = "GET_GALLERY_MEDIA_SUCCESS",
    GET_GALLERY_MEDIA_ERROR = "GET_GALLERY_MEDIA_ERROR",
    SAVE_GALLERY_MEDIA = "SAVE_GALLERY_MEDIA",
    SAVE_GALLERY_MEDIA_SUCCESS = "SAVE_GALLERY_MEDIA_SUCCESS",
    SAVE_GALLERY_MEDIA_ERROR = "SAVE_GALLERY_MEDIA_ERROR",
    PERCENT_UPLOADED = "PERCENT_UPLOADED",
    DELETE_GALLERY_MEDIA = "DELETE_GALLERY_MEDIA",
    DELETE_GALLERY_MEDIA_SUCCESS = "DELETE_GALLERY_MEDIA_SUCCESS",
    DELETE_GALLERY_MEDIA_ERROR = "DELETE_GALLERY_MEDIA_ERROR",
}

export enum CarouselMediaActionTypes {
    GET_CAROUSEL_DATA = "GET_CAROUSEL_DATA",
    GET_CAROUSEL_DATA_SUCCESS = "GET_CAROUSEL_DATA_SUCCESS",
    GET_CAROUSEL_DATA_ERROR = "GET_CAROUSEL_DATA_ERROR",
    SAVE_CAROUSEL_DATA = "SAVE_CAROUSEL_DATA",
    SAVE_CAROUSEL_DATA_SUCCESS = "SAVE_CAROUSEL_DATA_SUCCESS",
    SAVE_CAROUSEL_DATA_ERROR = "SAVE_CAROUSEL_DATA_ERROR",
    DELETE_CAROUSEL_DATA = "DELETE_CAROUSEL_DATA",
    DELETE_CAROUSEL_DATA_SUCCESS = "DELETE_CAROUSEL_DATA_SUCCESS",
    DELETE_CAROUSEL_DATA_ERROR = "DELETE_CAROUSEL_DATA_ERROR",
}